#!/usr/bin/env python3
import cs50
import sys
from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    tweets = get_user_timeline(sys.argv[1], 50)
    if tweets == None:
        sys.exit("No tweets found!")

    anal = Analyzer("positive-words.txt", "negative-words.txt")

    score = 0
    for tweet in tweets:
        score=anal.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))


if __name__ == "__main__":
    main()